import { StyleSheet } from "react-native";
import { themeColor } from "../controller/utils/constants";

export const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
    backgroundColor: "transparent",
  },
  container: {
    flex: 1,
    paddingTop: 10,
  },
  menu: {
    maxHeight: "100%",
    backgroundColor: "#0f3263c4",
    borderRadius: 28,
    width: "97%",
    margin: "auto",
  },
  topBar: {
    paddingHorizontal: 10,
    paddingBottom: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    elevation: 5,
    zIndex: 1000,
  },
  menuToggleButton: {
    backgroundColor: themeColor.primary,
    paddingVertical: 10,
    width: 60,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    elevation: 3,
    zIndex: 2000,
    marginBottom: 5,
  },

  arrowColumn: {
    alignItems: "center",
    justifyContent: "center",
  },
  dropdownContainer: {
    width: "45%",
    zIndex: 2000,
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
    padding: 5,
    marginVertical: 5,
    borderRadius: 16,
    color: "#000000",
    backgroundColor: "#f5f5f5",
    width: "auto",
    alignSelf: "center",
    textAlign: "center",
    borderWidth: 1,
  },
  dropdown: {
    borderColor: "#ccc",
    minHeight: 40,
    borderRadius: 18,
    backgroundColor: themeColor.dropDownbackgorund,
    color: themeColor.secondory,
  },
  dropdownPlaceholder: {
    color: themeColor.secondory,
    fontWeight: "bold",
  },
  dropdownLabel: {
    color: themeColor.secondory,
  },
  dropdownBox: {
    borderColor: "#ccc",
  },
  mapAreaPlaceholder: {
    height: 350,
    backgroundColor: "#e0e0e0",
    marginHorizontal: 35,
    borderRadius: 10,
    overflow: "hidden",
    zIndex: 1,
  },
  mapSection: {
    marginBottom: 20,
  },
  floorTitle: {
    fontSize: 18,
    marginTop: 10,
    fontWeight: "bold",
    textAlign: "center",
    color: themeColor.secondory,
    backgroundColor: themeColor.primary,
    width: "30%",
    margin: "auto",
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderRadius: 5,
    borderColor: "#176d6a",
  },
  mapImage: {
    width: "100%",
    height: "100%",
  },
  zoomableView: {
    flex: 1,
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  infoText: {
    margin: "auto",
    paddingTop: "50%",
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
    marginVertical: 5,
  },
  deleteButton: {
    backgroundColor: themeColor.deleteBackground,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 2,
    elevation: 5,
    width: "80%",
    margin: "auto",
    alignItems: "center",
    marginTop: 15,
  },
  deleteButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  deleteButtonBox: {
    alignItems: "center",
    marginBottom: 15,
  },
  imageWrapper: {
    width: "100%",
    aspectRatio: 0.67,
    alignSelf: "center",
    position: "absolute",
  },
  dropdownListItem: {
    padding: 15,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderColor: "#ccc",
  },
  dropdownListItemText: {
    color: "black",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  dropdownItemUsed: {
    backgroundColor: "#f0f0f0",
  },
  dropdownItemTextUsed: {
    color: "#a9a9a9",
    fontStyle: "italic",
  },
  dropdownItemSelected: {
    backgroundColor: themeColor.primary,
  },
  dropdownItemTextSelected: {
    color: themeColor.secondory,
    fontWeight: "bold",
  },

  //schedule

  headerRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
    backgroundColor: "#F8F8F8E6",
  },
  timeColumnHeader: { width: 50 },
  dayHeader: {
    width: 130,
    alignItems: "center",
    paddingVertical: 10,
    borderLeftWidth: 1,
    borderLeftColor: "#ddd",
  },
  dayHeaderText: {
    fontWeight: "bold",
    fontSize: 15,
    color: themeColor.primary,
  },
  scrollArea: { flex: 1 },
  gridContainer: { flexDirection: "row", paddingVertical: 10 },
  timeColumn: {
    width: 50,
    backgroundColor: "#ffffff85",
    zIndex: 10,
    backgroundColor: themeColor.defaultColor || "white",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  timeLabelBox: {
    justifyContent: "flex-start",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#ddd",
  },
  timeText: {
    fontSize: 10,
    color: "#000000",
    marginTop: -7,
    fontWeight: "bold",
  },
  dayColumn: {
    width: 130,
    position: "relative",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(0,0,0,0.1)",
  },
  gridLine: { borderTopWidth: 1, borderTopColor: "rgba(0,0,0,0.1)" },
  classBlock: {
    position: "absolute",
    left: 1,
    right: 1,
    borderRadius: 4,
    padding: 2,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.2)",
  },
  classTitle: { fontSize: 12, fontWeight: "bold", color: "#000" },
  classTime: { fontSize: 10, color: "#222" },

  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    backgroundColor: themeColor.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
  },
  fabText: { color: themeColor.secondory, fontSize: 30, fontWeight: "bold" },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    flex: 0,
    width: "90%",
    margin: 20,
    padding: 20,
    borderWidth: 2,
    borderRadius: 15,
    borderColor: themeColor.secondory,
    overflow: "hidden",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
    color: themeColor.secondory,
    backgroundColor: themeColor.primary,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#ffffff",
    color: "#000000",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
    borderColor: themeColor.secondory,
  },
  timeButton: {
    borderWidth: 1,
    borderColor: themeColor.secondory,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  timeButtonText: {
    color: "#000000",
    fontWeight: "bold",
    fontSize: 16,
  },
  timeRow: { flexDirection: "row", justifyContent: "space-between" },
  saveButton: {
    backgroundColor: themeColor.primary,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    elevation: 5,
    borderWidth: 2,
  },
  saveButtonText: { color: themeColor.secondory, fontWeight: "bold" },
  cancelText: {
    textAlign: "center",
    color: "white",
    marginTop: 15,
    backgroundColor: themeColor.secondory,
    color: themeColor.primary,
    paddingVertical: 8,
    fontWeight: "bold",
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 2,
    elevation: 5,
  },
});
